version: "3.7"
services: 
  mysql:
    container_name: ${MYSQL_NAME}
    image: mysql:5.7
    ports:
        - ${MYSQL_PORT}:3306
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
  phpmyadmin:
    container_name: ${PHPMYADMIN_NAME}
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_USER: root 
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    links:
      - mysql
  apachedrupal:
    container_name: ${DRUPAL_NAME}
    depends_on: 
      - mysql
    build: .
    ports: 
      - "${DRUPAL_PORT}:80"
    volumes: 
      - ./app:/app
    restart: always
volumes: 
  db_data: